version: '2'
services:
  appdata:
    image: tianon/true
    volumes:
      - .:/var/www/magento

  dbdata:
    image: tianon/true
    volumes:
      - /var/lib/mysql

  fpm:
    hostname: fpm.magento2.docker
    build: ./docker/7.0-fpm
    ports:
      - "9000"
    links:
      - db
    volumes_from:
      - appdata
    env_file:
      - ./docker/global.env
      - ./docker/composer.env

  cli:
    hostname: cli.magento2.docker
    build: ./docker/7.0-cli
    links:
      - db
#    This must be uncommented once std integration plan is removed
#    volumes:
#      - ~/.composer/cache:/root/.composer/cache
    volumes_from:
      - appdata
    env_file:
      - ./docker/global.env
      - ./docker/composer.env
  db:
    image: mariadb:10
    ports:
      - 3306
    volumes_from:
      - dbdata
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
  web:
    build: ./docker/nginx
    links:
      - fpm
      - db
    volumes_from:
      - appdata
    env_file:
      - ./docker/global.env
    environment:
      - VIRTUAL_HOST=magento2.docker
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect

