version: '2'
services:
  db:
    image: 'mariadb:10.2'
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
    hostname: db.magento2.docker
    ports:
      - '3306:3306'
    networks:
      magento:
        aliases:
          - db.magento2.docker
    volumes:
      - /var/lib/mysql
      - './.docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
  elasticsearch:
    image: 'magento/magento-cloud-docker-elasticsearch:5.2-1.0'
    networks:
      - magento
  fpm:
    image: 'test/php:7.2-fpm'
    ports:
      - 9000
    depends_on:
      - db
    extends: generic
    volumes:
      - '.:/ece-tools'
      - 'magento:/app:ro'
      - 'magento-vendor:/app/vendor:ro'
      - 'magento-generated:/app/generated:ro'
      - 'magento-var:/app/var:delegated'
      - 'magento-etc:/app/app/etc:delegated'
      - 'magento-static:/app/pub/static:delegated'
      - 'magento-media:/app/pub/media:delegated'
    networks:
      - magento
  build:
    image: 'test/php:7.2-cli'
    hostname: build.magento2.docker
    depends_on:
      - db
      - elasticsearch
    extends: generic
    volumes:
      - '.:/ece-tools'
      - 'magento:/app:rw'
      - 'magento-vendor:/app/vendor:rw'
      - 'magento-generated:/app/generated:rw'
      - 'magento-build-var:/app/var:delegated'
      - 'magento-build-etc:/app/app/etc:delegated'
      - 'magento-build-static:/app/pub/static:delegated'
      - 'magento-build-media:/app/pub/media:delegated'
      - '/app/.composer:delegated'
    networks:
      magento:
        aliases:
          - web.magento2.docker
  deploy:
    image: 'test/php:7.2-cli'
    hostname: deploy.magento2.docker
    depends_on:
      - db
      - elasticsearch
    extends: generic
    volumes:
      - '.:/ece-tools'
      - 'magento:/app:ro'
      - 'magento-vendor:/app/vendor:ro'
      - 'magento-generated:/app/generated:ro'
      - 'magento-var:/app/var:delegated'
      - 'magento-etc:/app/app/etc:delegated'
      - 'magento-static:/app/pub/static:delegated'
      - 'magento-media:/app/pub/media:delegated'
      - '/app/.composer:delegated'
    networks:
      magento:
        aliases:
          - deploy.magento2.docker
  web:
    image: 'test/nginx:1.9'
    hostname: web.magento2.docker
    depends_on:
      - fpm
    extends: generic
    volumes:
      - '.:/ece-tools'
      - 'magento:/app:ro'
      - 'magento-vendor:/app/vendor:ro'
      - 'magento-generated:/app/generated:ro'
      - 'magento-var:/app/var:delegated'
      - 'magento-etc:/app/app/etc:delegated'
      - 'magento-static:/app/pub/static:delegated'
      - 'magento-media:/app/pub/media:delegated'
    networks:
      magento:
        aliases:
          - web.magento2.docker
  varnish:
    image: 'magento/magento-cloud-docker-varnish:latest-1.0'
    environment:
      - VIRTUAL_HOST=magento2.docker
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
    ports:
      - '80:80'
    depends_on:
      - web
    networks:
      magento:
        aliases:
          - magento2.docker
  tls:
    image: 'magento/magento-cloud-docker-tls:latest-1.0'
    ports:
      - '443:443'
    external_links:
      - 'varnish:varnish'
    depends_on:
      - varnish
    networks:
      - magento
  generic:
    image: alpine
    environment:
      - 'PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip xsl redis'
    env_file:
      - ./.docker/composer.env
      - ./.docker/global.env
volumes:
  magento: {  }
  magento-vendor: {  }
  magento-generated: {  }
  magento-var: {  }
  magento-etc: {  }
  magento-static: {  }
  magento-media: {  }
  magento-build-var: {  }
  magento-build-etc: {  }
  magento-build-static: {  }
  magento-build-media: {  }
networks:
  magento:
    driver: bridge
