#!/usr/bin/env php
<?php

// TOOD: this doesn't work //require_once __DIR__ . '/autoload.php';
require_once '/app/app/autoload.php'; // Note: trying a different autoload.php

$command = new Magento\MagentoCloud\Command\SendPasswordResetEmail();
$application = new Symfony\Component\Console\Application();

$application->addCommands([$command]);
$application->setDefaultCommand($command->getName());

$application->run();
