#!/usr/bin/env php
<?php

require_once __DIR__ . '/autoload.php';

$command = new Magento\MagentoCloud\Command\SCDConfigDump();
$application = new Symfony\Component\Console\Application();

$application->addCommands([$command]);
$application->setDefaultCommand($command->getName());

$application->run();
