#!/usr/bin/env php
<?php

// TOOD: this doesn't work //require_once __DIR__ . '/autoload.php';
require_once '/app/app/autoload.php'; // Note: I had to use a different autoload.php to get this one working.  // TODO: Should we be using a different one?
require_once 'app/functions.php';  // TODO: added this require because of fatal error __() missing.  I think this function should probably be included a different way.

$command = new Magento\MagentoCloud\Command\SendPasswordResetEmail();
$application = new Symfony\Component\Console\Application();

$application->addCommands([$command]);
$application->setDefaultCommand($command->getName());

$application->run();
