#!/usr/bin/env php
<?php

require_once __DIR__ . '/autoload.php';

includeIfExists('Magento\MagentoCloud\Command\SCDConfigDump');
includeIfExists('Magento\MagentoCloud\Environment');
includeIfExists('Magento\MagentoCloud\Database');

$scdDump = new Magento\MagentoCloud\Command\SCDConfigDump();
$scdDump->execute();
