#!/usr/bin/env php
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
$container = require __DIR__ . '/bootstrap.php';

$application = new \Magento\MagentoCloud\Application($container);
$application->setDefaultCommand(\Magento\MagentoCloud\Command\ConfigDump::NAME);
$application->run();
