#!/usr/bin/env php
<?php

require_once __DIR__ . '/autoload.php';

$application = new \Magento\MagentoCloud\Application(
    new \Magento\MagentoCloud\Container\Container()
);
$application->setDefaultCommand('deploy');
$application->run();

